=== SamPons12/LMSGI_DAW1/UD4/ex_pack3_ud4_sam_pons/ex3.4/dtd_ex3.4.dtd
<!ELEMENT productes (futur+, divisa+, bono+, lletra+)>
<!ELEMENT futur (producte, mercat?, (madrid | nova_york | frankfurt | toquio))>
<!ELEMENT divisa (nom, canvi+, (madrid | nova_york | frankfurt | toquio))>
<!ELEMENT bono (pais_de_procedencia, valor_desitjat, valor_minim, valor_maxim, (madrid | nova_york | frankfurt | toquio))>
<!ELEMENT lletra (interes, emissor, (madrid | nova_york | frankfurt | toquio))>
<!ELEMENT producte (#PCDATA)>
<!ELEMENT mercat (#PCDATA)>
<!ELEMENT madrid EMPTY>
<!ELEMENT nova_york EMPTY>
<!ELEMENT frankfurt EMPTY>
<!ELEMENT toquio EMPTY>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT canvi (#PCDATA)>
<!ELEMENT pais_de_procedencia (#PCDATA)>
<!ELEMENT valor_desitjat (#PCDATA)>
<!ELEMENT valor_minim (#PCDATA)>
<!ELEMENT valor_maxim (#PCDATA)>
<!ELEMENT interes (#PCDATA)>
<!ELEMENT emissor (#PCDATA)>

<!ATTLIST futur preu CDATA #REQUIRED>
<!ATTLIST divisa preu CDATA #REQUIRED>
<!ATTLIST divisa estable (si | no) #IMPLIED>
<!ATTLIST bono preu CDATA #REQUIRED>
<!ATTLIST bono estable (si | no) #IMPLIED>
<!ATTLIST lletra preu CDATA #REQUIRED>

=== SamPons12/LMSGI_DAW1/UD4/ex_pack3_ud4_sam_pons/ex3.4/ex3.4.1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productes SYSTEM "dtd_ex3.4.dtd">

<productes>
    <futur preu="20000">
        <producte>Accio X</producte>
        <mercat>Alemanya</mercat>
        <madrid></madrid>
    </futur>

    <divisa preu="200" estable="si">
        <nom>Divisa X</nom>
        <canvi>Dolar</canvi>
        <toquio></toquio>
    </divisa>

    <bono preu="1000">
        <pais_de_procedencia>Alemnya</pais_de_procedencia>
        <valor_desitjat>100</valor_desitjat>
        <valor_minim>50</valor_minim>
        <valor_maxim>200</valor_maxim>
        <frankfurt></frankfurt>
    </bono>

    <lletra preu="30">
        <interes>2.5</interes>
        <emissor>USA</emissor>
        <nova_york></nova_york>
    </lletra>
</productes>
