=== SamPons12/LMSGI_DAW1/UD4/ex_pack3_ud4_sam_pons/ex3.3/dtd_ex3.3.dtd
<!ELEMENT demanat (llibre | quadern | llapis)*>
<!ELEMENT llibre EMPTY>
<!ELEMENT quadern EMPTY>
<!ELEMENT llapis (numero)>
<!ELEMENT numero (#PCDATA)>
    
<!ATTLIST llibre titol CDATA #REQUIRED>
<!ATTLIST quadern num_fulles CDATA #IMPLIED>

=== SamPons12/LMSGI_DAW1/UD4/ex_pack3_ud4_sam_pons/ex3.3/ex3.3.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE demanat SYSTEM "dtd_ex3.3.dtd">

<demanat>
    <llibre titol="Quijote"></llibre>
    <llibre titol="2"></llibre>
    <llibre titol="3"></llibre>
    <llibre titol="4"></llibre>
    <llapis>
        <numero>3</numero>
    </llapis>
    <llapis>
        <numero>5</numero>
    </llapis>
    <llibre titol="5"></llibre>
    <llibre titol="6"></llibre>
</demanat>
