=== SamPons12/LMSGI_DAW1/UD4/pack4_xml_sam_pons/factura.dtd
<!ELEMENT factura (capcalera, liniea+, total)>
  <!ELEMENT capcalera (data, client, proveidor)>
    <!ELEMENT data EMPTY>
    <!ELEMENT client EMPTY>
    <!ELEMENT proveidor EMPTY>
  <!ELEMENT liniea (article, numero_unitats, import_total)>
    <!ELEMENT article (descripcio, preu_no_iva, preu_iva)>
      <!ELEMENT descripcio (#PCDATA)>
      <!ELEMENT preu_no_iva (#PCDATA)>
      <!ELEMENT preu_iva (#PCDATA)>
    <!ELEMENT numero_unitats (#PCDATA)>
    <!ELEMENT import_total (#PCDATA)>
  <!ELEMENT total (subtotal_4, subtotal_10, subtotal_21, total_no_iva, total_iva)>
    <!ELEMENT subtotal_4 (#PCDATA)>
    <!ELEMENT subtotal_10 (#PCDATA)>
    <!ELEMENT subtotal_21 (#PCDATA)>
    <!ELEMENT total_no_iva (#PCDATA)>
    <!ELEMENT total_iva (#PCDATA)>

<!ATTLIST capcalera id ID #REQUIRED>
<!ATTLIST data dia CDATA #REQUIRED>
<!ATTLIST data mes CDATA #REQUIRED>
<!ATTLIST data any CDATA #REQUIRED>

<!ATTLIST client nom_fiscal CDATA #REQUIRED>
<!ATTLIST client nom_comercial CDATA #IMPLIED>
<!ATTLIST client nif CDATA #REQUIRED>
<!ATTLIST proveidor nom_fiscal CDATA #REQUIRED>
<!ATTLIST proveidor nom_comercial CDATA #IMPLIED>
<!ATTLIST proveidor nif CDATA #REQUIRED>

<!ATTLIST liniea id ID #REQUIRED>
<!ATTLIST liniea article_ref IDREF #REQUIRED>

<!ATTLIST article id ID #REQUIRED>
<!ATTLIST article tipus_iva (4 | 10 | 21) #REQUIRED>

=== SamPons12/LMSGI_DAW1/UD4/pack4_xml_sam_pons/factura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">

<factura>
  <capcalera id="DER">
    <data dia="04" mes="04" any="2024"/>
    <client nom_fiscal="Joan Marques" nom_comercial="Joan S.L." nif="41749829E"/>
    <proveidor nom_fiscal="Pere Moll" nif="4375423Z"/>
  </capcalera>

  <liniea id="A" article_ref="Z">
    <article id="Z" tipus_iva="21">
      <descripcio>botella de agua</descripcio>
      <preu_no_iva>1</preu_no_iva>
      <preu_iva>2</preu_iva>
    </article>
    <numero_unitats>10</numero_unitats>
    <import_total>10</import_total>
  </liniea>

  <total>
    <subtotal_4>0</subtotal_4>
    <subtotal_10>0</subtotal_10>
    <subtotal_21>20</subtotal_21>
    <total_no_iva>10</total_no_iva>
    <total_iva>20</total_iva>  
  </total>

</factura>

=== SamPons12/LMSGI_DAW1/UD4/pack4_xml_sam_pons/factura2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura SYSTEM "factura.dtd">

<factura>
  <capcalera id="DER">
    <data dia="04" mes="04" any="2024"/>
    <client nom_fiscal="Joan Marques"  nif="41749829E"/>
    <proveidor nom_fiscal="Pere Moll" nif="4375423Z"/>
  </capcalera>

  <liniea id="A" article_ref="Z">
    <article id="Z" tipus_iva="21">
      <descripcio>botella de  agua</descripcio>
      <preu_no_iva>1</preu_no_iva>
      <preu_iva>2</preu_iva>
    </article>
    <numero_unitats>10</numero_unitats>
    <import_total>10</import_total>
  </liniea>

    <liniea id="B" article_ref="S">
    <article id="S" tipus_iva="21">
      <descripcio>botella de nestea</descripcio>
      <preu_no_iva>2</preu_no_iva>
      <preu_iva>4</preu_iva>
    </article>
    <numero_unitats>10</numero_unitats>
    <import_total>20</import_total>
  </liniea>

    <liniea id="C" article_ref="V">
    <article id="V" tipus_iva="21">
      <descripcio>botella de  fanta</descripcio>
      <preu_no_iva>1.5</preu_no_iva>
      <preu_iva>2.5</preu_iva>
    </article>
    <numero_unitats>5</numero_unitats>
    <import_total>7.5</import_total>
  </liniea>

  <total>
    <subtotal_4>0</subtotal_4>
    <subtotal_10>0</subtotal_10>
    <subtotal_21></subtotal_21>
    <total_no_iva>25</total_no_iva>
    <total_iva>37.5</total_iva>  
  </total>

</factura>
