=== SamPons12/LMSGI_DAW1/UD4/ex_pack2_ud4_sam_pons/dtd_ex2.2.dtd
<!ELEMENT comanda (tractor+)>
    <!ELEMENT tractor (component+)>
    <!ELEMENT component (data_entrega, pes, nombre_serie, km_maxims?)>
    <!ELEMENT data_entrega EMPTY>
    <!ELEMENT pes (#PCDATA)>
    <!ELEMENT nombre_serie (#PCDATA)>
    <!ELEMENT element-name (#PCDATA)>
    <!ELEMENT km_maxims (#PCDATA)>

    <!ATTLIST component fabricant CDATA #REQUIRED>
    <!ATTLIST component fragil (true | false) #REQUIRED>
    <!ATTLIST data_entrega dia CDATA #IMPLIED>
    <!ATTLIST data_entrega mes CDATA #REQUIRED>
    <!ATTLIST data_entrega any CDATA #REQUIRED>
    <!ATTLIST pes unitat (quilos | grams) #REQUIRED>

=== SamPons12/LMSGI_DAW1/UD4/ex_pack2_ud4_sam_pons/ex_2.2_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "dtd_ex2.2.dtd">

<comanda>
    <tractor>
        <component fabricant="BMW" fragil="true">
            <data_entrega dia="12" mes="07" any="2022"/>
            <pes unitat="quilos">30</pes>
            <nombre_serie>30495746HF</nombre_serie>
            <km_maxims>150000</km_maxims>
        </component>
        <component fabricant="Lamborghini" fragil="false">
            <data_entrega dia="19" mes="02" any="2023"/>
            <pes unitat="quilos">100</pes>
            <nombre_serie>306573936LF</nombre_serie>
            <km_maxims>200000</km_maxims>
        </component>
    </tractor>
    <tractor>
        <component fabricant="Mercedes" fragil="true">
            <data_entrega mes="05" any="2021"/>
            <pes unitat="grams">500</pes>
            <nombre_serie>845429347LK</nombre_serie>
        </component>
    </tractor>
</comanda>

=== SamPons12/LMSGI_DAW1/UD4/ex_pack2_ud4_sam_pons/ex_2.2_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comanda SYSTEM "dtd_ex2.2.dtd">

<comanda>
    <tractor>
        <component fabricant="BMW" fragil="true">
            <data_entrega dia="12" mes="07" any="2022"/>
            <pes unitat="quilos">30</pes>
            <nombre_serie>30495746HF</nombre_serie>
            <km_maxims>150000</km_maxims>
        </component>
        <component fabricant="Lamborghini" fragil="false">
            <data_entrega dia="19" mes="02" any="2023"/>
            <pes unitat="quilos">100</pes>
            <nombre_serie>306573936LF</nombre_serie>
        </component>
    </tractor>
</comanda>
